core/urls.py
from django.urls import path
<<<<<<< HEAD
from django.conf import settings
from django.conf.urls.static import static  
from . import views
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from .views import MyEventsAPI, EventCancelAPI

=======
from . import views
>>>>>>> d777e06a7afec3224da65659784b0ef318e76793

app_name = 'core'

urlpatterns = [
<<<<<<< HEAD
    # -----------------------------
    # Rotas do sistema principal
    # -----------------------------
    path('', views.home_view, name='home'),
    path('events/', views.event_list, name='events'),
    path('events/<int:event_id>/', views.event_detail, name='event_detail'),
    path('events/new/', views.create_event_view, name='event_form'),
=======
    path('', views.home_view, name='home'),
    path('events/', views.event_list, name='events'),
    path('events/<int:event_id>/', views.event_detail, name='event_detail'),
    path('events/new/', views.create_event_view, name='event_form'),  # ✅ nova rota
>>>>>>> d777e06a7afec3224da65659784b0ef318e76793
    path('profile/', views.profile_view, name='profile'),
    path('profile/edit/', views.edit_profile_view, name='edit_profile'),
    path('register/', views.register_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
<<<<<<< HEAD
    path('certificado/<int:event_id>/<int:user_id>/', views.emitir_certificado, name='emitir_certificado'),

    # -----------------------------
    # API JWT
    # -----------------------------
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    # -----------------------------
    # API Eventos
    # -----------------------------
    path('api/events/', views.EventListAPI.as_view(), name='api_events_list'),
    path('api/events/create/', views.EventCreateAPI.as_view(), name='api_event_create'),
    path('api/events/<int:event_id>/register/', views.EventRegisterAPI.as_view(), name='api_event_register'),

# Meus eventos (inscrições do usuário)
    path('api/my-events/', MyEventsAPI.as_view(), name='api_my_events'),

# Cancelar inscrição
    path('api/events/<int:event_id>/cancel/', EventCancelAPI.as_view(), name='api_event_cancel'),
]
# Servir arquivos de mídia em DEBUG
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
=======
    path('events/new/', views.create_event_view, name='event_form'),

]
>>>>>>> d777e06a7afec3224da65659784b0ef318e76793

sgea_project/urls.py
from django.contrib import admin
from django.urls import path, include
<<<<<<< HEAD
from django.conf import settings
from django.conf.urls.static import static
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework.permissions import AllowAny

schema_view = get_schema_view(
    openapi.Info(
        title="SGEA API",
        default_version="v1",
        description="API do Sistema de Gestão de Eventos Acadêmicos",
    ),
    public=True,
    permission_classes=[AllowAny],
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),  # inclui as urls do app
    path('docs/', schema_view.with_ui('swagger', cache_timeout=0), name='swagger-docs'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='redoc'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
=======

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),  # todas as rotas do core
]
>>>>>>> d777e06a7afec3224da65659784b0ef318e76793

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}SGEA{% endblock %}</title>
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700&family=Roboto+Slab:wght@500;700&display=swap" rel="stylesheet">
<<<<<<< HEAD
  <link rel="stylesheet" href="https://code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js"></script>

=======
>>>>>>> d777e06a7afec3224da65659784b0ef318e76793
</head>
<body>
  <div class="body-wrapper">
    <!-- Cabeçalho -->
    <header>
      <div class="logo">
  <a href="{% url 'core:home' %}">
    <img src="{% static 'image/sgea.png' %}" alt="Logo SGEA" style="height: 80px;">
  </a>
</div>

      <nav>
        <a href="{% url 'core:home' %}" class="btn">Home</a>
        <a href="{% url 'core:events' %}" class="btn">Eventos</a>
        {% if user.is_authenticated %}
          <a href="{% url 'core:profile' %}" class="btn">Meu Perfil</a>
          <a href="{% url 'core:logout' %}" class="btn cancel">Sair</a>
        {% else %}
          <a href="{% url 'core:login' %}" class="btn">Entrar</a>
          
        {% endif %}
      </nav>
    </header>

    <!-- Conteúdo principal -->
    <main>
      {% block content %}{% endblock %}
      <div style="height: 1px;"></div>
    </main>

    <!-- Rodapé -->
    <footer>
      <p>&copy; {{ now.year }} SGEA - CEUB. Todos os direitos reservados.</p>
    </footer>
  </div>
</body>
</html>